In [1]:
import pandas as pd

In [94]:
matches2=pd.read_csv('https://raw.githubusercontent.com/Jhovanylara/FIFA-WorldCup2022/master/config/WorldCupMatches.csv')
matches=matches2.copy()

In [95]:
matches=matches.dropna(how='all')
matches.drop(columns=['Win conditions','Attendance','City','Stadium','Referee','Assistant 1', 'Assistant 2', 'Home Team Initials','Away Team Initials'], inplace=True)
def wins(row):
    if row['Home Team Goals']> row['Away Team Goals']:
        return 'Won'
    if row['Home Team Goals']==row['Away Team Goals']:
        return 'Tied'
    if row['Home Team Goals']< row['Away Team Goals']:
        return 'Lost'

matches['Home result']=matches.apply(lambda row: wins(row), axis=1)

    
matches.tail()

,Year,Datetime,Stage,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Half-time Home Goals,Half-time Away Goals,RoundID,MatchID,Home result
847,2014.0,05 Jul 2014 - 17:00,Quarter-finals,Netherlands,0.0,0.0,Costa Rica,0.0,0.0,255953.0,300186488.0,Tied
848,2014.0,08 Jul 2014 - 17:00,Semi-finals,Brazil,1.0,7.0,Germany,0.0,5.0,255955.0,300186474.0,Lost
849,2014.0,09 Jul 2014 - 17:00,Semi-finals,Netherlands,0.0,0.0,Argentina,0.0,0.0,255955.0,300186490.0,Tied
850,2014.0,12 Jul 2014 - 17:00,Play-off for third place,Brazil,0.0,3.0,Netherlands,0.0,2.0,255957.0,300186502.0,Lost
851,2014.0,13 Jul 2014 - 16:00,Final,Germany,1.0,0.0,Argentina,0.0,0.0,255959.0,300186501.0,Won

In [240]:
matches.replace({'German DR':'Germany','German FR':'Germany'})

,Year,Datetime,Stage,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Half-time Home Goals,Half-time Away Goals,RoundID,MatchID,Home result
0,1930.0,13 Jul 1930 - 15:00,Group 1,France,4.0,1.0,Mexico,3.0,0.0,201.0,1096.0,Won
1,1930.0,13 Jul 1930 - 15:00,Group 4,USA,3.0,0.0,Belgium,2.0,0.0,201.0,1090.0,Won
2,1930.0,14 Jul 1930 - 12:45,Group 2,Yugoslavia,2.0,1.0,Brazil,2.0,0.0,201.0,1093.0,Won
3,1930.0,14 Jul 1930 - 14:50,Group 3,Romania,3.0,1.0,Peru,1.0,0.0,201.0,1098.0,Won
4,1930.0,15 Jul 1930 - 16:00,Group 1,Argentina,1.0,0.0,France,0.0,0.0,201.0,1085.0,Won
...,...,...,...,...,...,...,...,...,...,...,...,...
847,2014.0,05 Jul 2014 - 17:00,Quarter-finals,Netherlands,0.0,0.0,Costa Rica,0.0,0.0,255953.0,300186488.0,Tied
848,2014.0,08 Jul 2014 - 17:00,Semi-finals,Brazil,1.0,7.0,Germany,0.0,5.0,255955.0,300186474.0,Lost
849,2014.0,09 Jul 2014 - 17:00,Semi-finals,Netherlands,0.0,0.0,Argentina,0.0,0.0,255955.0,300186490.0,Tied
850,2014.0,12 Jul 2014 - 17:00,Play-off for third place,Brazil,0.0,3.0,Netherlands,0.0,2.0,255957.0,300186502.0,Lost
851,2014.0,13 Jul 2014 - 16:00,Final,Germany,1.0,0.0,Argentina,0.0,0.0,255959.0,300186501.0,Won

In [ ]:
players=pd.read_csv('WorldCupPlayers.csv')
players.head()

In [ ]:
cups=pd.read_csv('WorldCups.csv')
cups.tail()

In [226]:
from config.db import engine
Team='Germany'

R1=f'''SELECT Year, Stage, `Home Team Name`, `Away Team Name`, `Home Team Goals`, `Away Team Goals`, `Half-time Home Goals`, `Half-time Away Goals`, `Home result`     
FROM matches     
WHERE `Home Team Name` LIKE '{Team}'
;'''


df1=pd.read_sql(R1, engine)

In [204]:
df1

Empty DataFrame
Columns: [Year, Stage, Home Team Name, Home Team Goals, Away Team Goals, Half-time Home Goals, Half-time Away Goals, Home result]
Index: []

In [163]:
if df1.empty:
    print (f"Es la primera participación de {Team} en copas del mundo.")
else:
    G1=df1['Home Team Goals'].sum()
    G2=df1['Away Team Goals'].sum()
    G3=df1['Half-time Home Goals'].sum()
    G4=df1['Half-time Away Goals'].sum()
    partidos=df1['Year'].count()
    wins_local=df1['Home result'].value_counts()['Won']
    lost_local=df1['Home result'].value_counts()['Lost']
    tied_local=df1['Home result'].value_counts()['Tied']

    print (f"{Team} de local ha anotado {G1} goles y ha recibido {G3} goles, en {partidos} partidos.")
    print (f"En el primer tiempo anotó {G3} goles y recibió {G4} goles.")
    print (f"El {round((1-G3/G1)*100,1)}% de sus goles los hace en el segundo tiempo.")
    print (f"El {round((1-G4/G2)*100,1)}% de goles recibidos son en el segundo tiempo.")
    print (f"Ha ganado como local {wins_local} partidos, ha perdido {lost_local} y ha empatado {tied_local} partidos. Con una tasa de victorias del {round((wins_local/partidos)*100,1)}%")

Ecuador de local ha anotado 60 goles y ha recibido 15 goles, en 60 partidos.
En el primer tiempo anotó 15 goles y recibió 30 goles.
El 75.0% de sus goles los hace en el segundo tiempo.
El 33.3% de goles recibidos son en el segundo tiempo.
Ha ganado como local 30 partidos, ha perdido 15 y ha empatado 15 partidos. Con una tasa de victorias del 50.0%

In [227]:
from config.db import engine

R1=f'''SELECT Year, Stage, `Away Team Name`, `Home Team Name`,`Home Team Goals`, `Away Team Goals`, `Half-time Home Goals`, `Half-time Away Goals`, `Home result`
    FROM matches
    WHERE `Away Team Name`='{Team}'
    ;'''

df2=pd.read_sql(R1, engine)

In [228]:
df2

,Year,Stage,Away Team Name,Home Team Name,Home Team Goals,Away Team Goals,Half-time Home Goals,Half-time Away Goals,Home result
0,1934,Semi-finals,Germany,Czechoslovakia,3,1,1,0,Won
1,1938,First round,Germany,Switzerland,1,1,0,0,Tied
2,1938,First round,Germany,Switzerland,4,2,1,2,Won
3,1994,Quarter-finals,Germany,Bulgaria,2,1,0,0,Won
4,2002,Group E,Germany,Cameroon,0,2,0,0,Lost
...,...,...,...,...,...,...,...,...,...
289,2014,Group G,Germany,USA,0,1,0,0,Lost
290,2014,Quarter-finals,Germany,France,0,1,0,1,Lost
291,2014,Semi-finals,Germany,Brazil,1,7,0,5,Lost
292,2014,Quarter-finals,Germany,France,0,1,0,1,Lost
293,2014,Semi-finals,Germany,Brazil,1,7,0,5,Lost

In [238]:
lista=df2['Home Team Name'].unique()
lista
Enfrentamientos=[]
for i in lista:
    a=df2[df2['Home Team Name']==i]['Home Team Name'].count()
    Enfrentamientos.append(a)
Enfrentamientos

Rivales=pd.DataFrame(list(zip(lista,Enfrentamientos)), columns=['Rival', 'Enfrentamientos'])
Rivales=Rivales.sort_values(["Enfrentamientos"], ascending=False)
Rivales

             Rival  Enfrentamientos
1      Switzerland               42
9           France               42
10          Brazil               42
0   Czechoslovakia               21
2         Bulgaria               21
3         Cameroon               21
4          Ecuador               21
5            Ghana               21
6        Argentina               21
7          Uruguay               21
8              USA               21

In [239]:
import plotly.graph_objects as go
import streamlit as st

trace  = go.Bar(
                x=Rivales['Rival'].tolist(),
                y=Rivales['Enfrentamientos'].tolist(),
                showlegend = False
                )

layout = go.Layout(                                    
                xaxis_title='Rivales',
                yaxis_title='Cantidad enfrentamientos'
                )
data = [trace]
fig = go.Figure(data=data,layout = layout)
st.plotly_chart(fig)

2022-11-18 18:08:10.163
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run c:\Users\Jhovany Lara\AppData\Local\Programs\Python\Python310\lib\site-packages\ipykernel_launcher.py [ARGUMENTS]

DeltaGenerator(_root_container=0, _provided_cursor=None, _parent=None, _block_type=None, _form_data=None)

In [233]:
a=df2[df2['Home Team Name']=='USA']['Home Team Name'].count()
a

21

In [232]:
lista

array(['Czechoslovakia', 'Switzerland', 'Bulgaria', 'Cameroon', 'Ecuador',
       'Ghana', 'Argentina', 'Uruguay', 'USA', 'France', 'Brazil'],
      dtype=object)

In [175]:
tied_visit=df2[df2['Home result']=='Lost']['Home result'].count()
tied_visit

30

In [167]:
G5=df2['Home Team Goals'].sum()
G6=df2['Away Team Goals'].sum()
G7=df2['Half-time Home Goals'].sum()
G8=df2['Half-time Away Goals'].sum()
partidos_visit=df2['Year'].count()
wins_visit=df2[df2['Home result']=='Lost']['Home result'].count() #Se pone como Lost porque al ser visitante, si ha perido el local, ha ganado el visitante.
lost_visit=df2[df2['Home result']=='Won']['Home result'].count()
tied_visit=df2[df2['Home result']=='Tied']['Home result'].count()
print (f"{Team} de visitante ha anotado {G6} goles y ha recibido {G5} goles, en {partidos_visit} partidos.")
print (f"En el primer tiempo anotó {G8} goles y recibió {G7} goles.")
print (f"El {round((1-G8/G6)*100,1)}% de sus goles los hace en el segundo tiempo.")
print (f"El {round((1-G7/G5)*100,1)}% de goles recibidos son en el segundo tiempo.")
print (f"Ha ganado como visitante {wins_visit} partidos, ha perdido {lost_visit} y ha empatado {tied_visit} partidos. Con una tasa de victorias del {round((wins_visit/partidos_visit)*100,1)}%")

Ecuador de visitante ha anotado 90 goles y ha recibido 120 goles, en 90 partidos.
En el primer tiempo anotó 60 goles y recibió 60 goles.
El 33.3% de sus goles los hace en el segundo tiempo.
El 50.0% de goles recibidos son en el segundo tiempo.
Ha ganado como visitante 30 partidos, ha perdido 60 y ha empatado 0 partidos. Con una tasa de victorias del 33.3%

In [144]:
Anotados=G1+G6
Recibidos=G2+G5
Anotados1T=G3+G8
Recibidos1T=G4+G7
Partidos_totales=partidos+partidos_visit
wins=wins_local+wins_visit
lost=lost_local+lost_visit
tied=tied_local+tied_visit

print (f"{Team} en total ha anotado {Anotados} goles y ha recibido {Recibidos} goles, en {Partidos_totales} partidos.")
print (f"En el primer tiempo anotó {Anotados1T} goles y recibió {Recibidos1T} goles")
print (f"El {round((1-G7/G5)*100,1)}% de sus goles los hace en el segundo tiempo.({Anotados-56})")
print (f"El {round((1-G8/G6)*100,1)}% de goles recibidos son en el segundo tiempo.")
print (f"Ha ganado como visitante {wins} partidos, ha perdido {lost} y ha empatado {tied} partidos. Con una tasa de victorias del {round((wins/Partidos_totales)*100,1)}%.")

Argentina en total ha anotado 133 goles y ha recibido 85 goles, en 81 partidos.
En el primer tiempo anotó 56 goles y recibió 30 goles
El 61.0% de sus goles los hace en el segundo tiempo.(77)
El 63.6% de goles recibidos son en el segundo tiempo.
Ha ganado como visitante 44 partidos, ha perdido 22 y ha empatado 15 partidos. Con una tasa de victorias del 54.3%.